# MIT License
#
# SPDX-FileCopyrightText: Copyright (c) 2022 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
name: 'qpdf-action'
description: 'Install qpdf'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'qpdf/qpdf'
        path: 'qpdf'
    - run: |
        sudo apt-get update --yes --fix-missing
        sudo apt-get install --yes libssl-dev libjpeg-dev
      shell: bash
    - run: |
        cd qpdf || exit 1
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build build
        sudo cmake --install build
        cd ..
        rm -rf qpdf
        export LD_LIBRARY_PATH=/usr/local/lib
        sudo ldconfig
        qpdf --version
      shell: bash
